force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountManagerAssignment.cls
public with sharing class AccountManagerAssignment implements Schedulable {
    public void execute(SchedulableContext context) {
        List<User> accountManagers;
        List<Account> unassignedAccounts = [SELECT Id FROM Account WHERE Account_Manager__c = NULL];
        Iterator<Account> accountIterator = unassignedAccounts.iterator();

        while(accountIterator.hasNext()){
            Account unassignedAccount = accountIterator.next();
            if(accountManagers == null || accountManagers.isEmpty()){
                accountManagers = fetchAccountManager();
            }
            unassignedAccount.Account_Manager__c = accountManagers.remove(0).Id;
        }
        update unassignedAccounts;
    }

    private static List<User> fetchAccountManager(){
        List<User> accountManagers = [SELECT Id, (SELECT Id FROM Account_Managers__r) FROM User WHERE ProfileId = :GlobalConstants.ACCOUNT_MANAGER_PROFILE];
        accountManagers.sort();
        return accountManagers;
    }

    private class UserComparator implements Comparator<User> {
        public Integer compare(User user1, User user2) {
            return user1.Account_Managers__r.size() > user2.Account_Managers__r.size() ? 1 :
                user1.Account_Managers__r.size() < user2.Account_Managers__r.size() ? -1 : 0;
        }
    }
}